package com.manz.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WORDS".
 */
public class Words {

    private Long id;
    private String word;
    private Integer variant;
    private String meaning;
    private Double ratio;

    public Words() {
    }

    public Words(Long id) {
        this.id = id;
    }

    public Words(Long id, String word, Integer variant, String meaning, Double ratio) {
        this.id = id;
        this.word = word;
        this.variant = variant;
        this.meaning = meaning;
        this.ratio = ratio;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public Integer getVariant() {
        return variant;
    }

    public void setVariant(Integer variant) {
        this.variant = variant;
    }

    public String getMeaning() {
        return meaning;
    }

    public void setMeaning(String meaning) {
        this.meaning = meaning;
    }

    public Double getRatio() {
        return ratio;
    }

    public void setRatio(Double ratio) {
        this.ratio = ratio;
    }

    public String getUrl() {
        return (ratio > -1) ? "http://appsculture.com/vocab/images/" + getId() + ".png" : null;
    }
}
